{
 "title": "Integration Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Resource Use of Last 5 Jobs",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cloud_hpc_bridge_job_seff_metrics{metric=\"BiUn\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_seff_metrics{metric=\"Nod\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_seff_metrics{metric=\"CoPeNod\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_sacct_metrics{metric=\"AcNod\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_sacct_metrics{metric=\"RqCPUS\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_sacct_metrics{metric=\"AcCPUS\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_sacct_metrics{metric=\"AvCPUFreqkhz\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_seff_metrics{metric=\"CPUEffPe\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_seff_metrics{metric=\"CPUEffSec\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_seff_metrics{metric=\"CPUUSec\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_seff_metrics{metric=\"JoWaClTISec\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_sacct_metrics{metric=\"CPUTiSec\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_sacct_metrics{metric=\"AvCPUSec\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_sacct_metrics{metric=\"PlaCPUSec\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_sacct_metrics{metric=\"ToCPUSec\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_seff_metrics{metric=\"MemEffPe\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_seff_metrics{metric=\"MemEffByte\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_seff_metrics{metric=\"MemUtiByte\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_sacct_metrics{metric=\"AvDiReByte\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_sacct_metrics{metric=\"AvDiWrByte\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_sacct_metrics{metric=\"AvPas\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_sacct_metrics{metric=\"AvRSS\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_sacct_metrics{metric=\"AvVMSi\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_sacct_metrics{metric=\"StTi\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_sacct_metrics{metric=\"SuTi\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_sacct_metrics{metric=\"EnTi\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_sacct_metrics{metric=\"PlaSec\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_sacct_metrics{metric=\"TiLiSec\"}"
    }
   ]
  },
  {
   "title": "Cloud-HPC Pipeline Max Times",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cloud_hpc_bridge_job_time_metrics{area=\"components\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_time_metrics{area=\"gather\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_time_metrics{area=\"job\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_time_metrics{area=\"pipeline\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_time_metrics{area=\"ray-job\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_time_metrics{area=\"workflow\"}"
    }
   ]
  },
  {
   "title": "Cloud-HPC Pipeline Mean Times",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cloud_hpc_bridge_job_time_metrics{area=\"components\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_time_metrics{area=\"gather\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_time_metrics{area=\"job\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_time_metrics{area=\"pipeline\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_time_metrics{area=\"ray-job\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_time_metrics{area=\"workflow\"}"
    }
   ]
  },
  {
   "title": "Porter Max Times",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cloud_hpc_bridge_job_time_metrics{area=\"bridges\", collector=\"porter\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_time_metrics{area=\"jobs\", collector=\"porter\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_time_metrics{area=\"task\", collector=\"porter\"}"
    }
   ]
  },
  {
   "title": "Porter Mean Times",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cloud_hpc_bridge_job_time_metrics{area=\"bridges\", collector=\"porter\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_time_metrics{area=\"jobs\", collector=\"porter\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_time_metrics{area=\"task\", collector=\"porter\"}"
    }
   ]
  },
  {
   "title": "Submitter Max Times",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cloud_hpc_bridge_job_time_metrics{collector=\"user@example.com-submitter\", area=\"bridge\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_time_metrics{collector=\"user@example.com-submitter\", area=\"cancel\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_time_metrics{collector=\"user@example.com-submitter\", area=\"monitor\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_time_metrics{collector=\"user@example.com-submitter\", area=\"setup\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_time_metrics{collector=\"user@example.com-submitter\", area=\"submit\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_time_metrics{collector=\"user@example.com-submitter\", area=\"task\"}"
    }
   ]
  },
  {
   "title": "Submitter Mean Times",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cloud_hpc_bridge_job_time_metrics{collector=\"user@example.com-submitter\", area=\"bridge\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_time_metrics{collector=\"user@example.com-submitter\", area=\"cancel\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_time_metrics{collector=\"user@example.com-submitter\", area=\"monitor\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_time_metrics{collector=\"user@example.com-submitter\", area=\"setup\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_time_metrics{collector=\"user@example.com-submitter\", area=\"submit\"}"
    },
    {
     "expr": "cloud_hpc_bridge_job_time_metrics{collector=\"user@example.com-submitter\", area=\"task\"}"
    }
   ]
  }
 ]
}