apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlflow

configMapGenerator:
- name: mlflow-configmap
  env: config.env
  behavior: merge

secretGenerator:
- name: mlflow-secrets
  envs:
  - secret.env

bases:
  - ../../base
  - ../../postgres
  - ../../minio
