apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlflow

configMapGenerator:
- name: mlflow-configmap
  envs:
    - config.env
  behavior: merge

secretGenerator:
- name: mlflow-secrets
  envs:
    - secret.env

# patch mlflow deployment
patches:
- path: mlflow-path-s3.yaml
  target:
    kind: Deployment
    name: mlflow

resources:
  - ../../base
  - ../../postgres
  - ../../minio
