version: '3.8'

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: no
    ports:
      - '127.0.0.1:7200:8080'
    environment:
     - WEBUI_AUTH=False
    network_mode: host
    volumes:
      - open-webui:/app/backend/data

volumes:
  open-webui: {}