version: '3.8'

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16

services:
  ollama: 
    image: ollama/ollama:0.3.6
    container_name: ollama
    hostname: ollama
    restart: no
    ports:
      - '127.0.0.1:11434:11434'
    environment:
     - WEBUI_AUTH=False
    network_mode: host
    volumes:
      - ollama:/root/.ollama
  webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: webui
    hostname: webui
    restart: no
    ports:
      - '127.0.0.1:7200:8080'
    environment:
     - WEBUI_AUTH=False
    network_mode: host
    volumes:
      - open-webui:/app/backend/data

volumes:
  ollama: {}
  open-webui: {}