apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlflow

bases:
- cloudsql-proxy
- ../../base

secretGenerator:
- name: mlflow-secret
  behavior: merge
  literals:
    - DB_PASSWORD=""

configMapGenerator:
- name: mlflow-install-config
  env: params.env
  behavior: create
- name: mlflow-configmap
  env: config.env
  behavior: merge
