apiVersion: v1
kind: Service
metadata:
   name: remote-ray-bridge 
   annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: '0'
spec:
   type: ClusterIP
   ports:
   - protocol: TCP
     port: 0
     targetPort: 0 