version: '3.8'

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  submitter:
    image: t9k4b5ndjok1/cloud-hpc-integration:submitter_v1.00.0
    restart: no
    ports:
      - '127.0.0.1:5556:5556'
    networks:
      app_network:
        ipv4_address: 172.28.0.30
    secrets:
      - metadata
      - mahti_key
      - bridge_key

secrets:
  metadata:
    file: ()
  mahti_key:
    file: ()
  bridge_key:
    file: ()