version: '3.8'

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  dev-redis:
    image: redis
    restart: no
    ports:
      - '127.0.0.1:6379:6379'
    networks:
      app_network:
        ipv4_address: 172.28.0.2