apiVersion: v1
kind: ServiceAccount
metadata:
  name: porter-sa
  namespace: integration
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: porter-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: porter-binding
subjects:
  - kind: ServiceAccount
    name: porter-sa
    namespace: integration
roleRef:
  kind: ClusterRole
  name: porter-role
  apiGroup: rbac.authorization.k8s.io
  