apiVersion: v1
kind: Service
metadata:
  name: porter-service
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '5555'
spec:
  selector: 
    app: porter-server
  ports:
    - port: 5555
      targetPort: 5555